In [310]:
import pandas as pd
import numpy as np

### 1. Create a new file named `model_evaluation.py` or `model_evaluation.ipynb` for these exercises.

### 2. Given the following confusion matrix, evaluate (by hand) the model's performance.

|               | pred dog   | pred cat   |
|:------------  |-----------:|-----------:|
| actual dog    |         46 |         7  |
| actual cat    |         13 |         34 |

> 'dog' is my **positive**

> 'cat' is my **negative**

In [311]:
#predicted dog, was dog
tp = 46 

#predicted cat, was cat
tn = 34 

#predicted dog, was cat
fp = 13 

#predicted cat, was dog
fn = 7 

- In the context of this problem, what is a false positive?

In [312]:
#predicted dog, was cat
fp = 13

- In the context of this problem, what is a false negative?

In [313]:
#predicted cat, was dog
fn = 7 

- How would you describe this model?

In [314]:
def model_accuracy(tp,tn,fp,fn):
    return round(((tp + tn) / (tp + tn + fp + fn)),2)

def model_precision(tp,fp):
    return round(((tp)/(tp+fp)),2)

def model_recall(tp,fn):
    return round((tp)/(tp+fn),2)

In [315]:
model_accuracy(tp,tn,fp,fn)

0.8

> this model accurately predicts cat or dog 80% of the time

### 3. You are working as a datascientist working for Codeup Cody Creator (C3 for short), a rubber-duck manufacturing plant.

### Unfortunately, some of the rubber ducks that are produced will have defects. Your team has built several models that try to predict those defects, and the data from their predictions [can be found here](https://ds.codeup.com/data/c3.csv).

### Use the predictions dataset and pandas to help answer the following questions:

In [369]:
df_3= pd.read_csv('c3.csv')

In [370]:
df_3

actual     model1     model2     model3
0    No Defect  No Defect     Defect  No Defect
1    No Defect  No Defect     Defect     Defect
2    No Defect  No Defect     Defect  No Defect
3    No Defect     Defect     Defect     Defect
4    No Defect  No Defect     Defect  No Defect
..         ...        ...        ...        ...
195  No Defect  No Defect     Defect     Defect
196     Defect     Defect  No Defect  No Defect
197  No Defect  No Defect  No Defect  No Defect
198  No Defect  No Defect     Defect     Defect
199  No Defect  No Defect  No Defect     Defect

[200 rows x 4 columns]

> 'Defect' is my **positive**

> 'No Defect' is my **negative**

- An internal team wants to investigate the cause of the manufacturing defects. They tell you that they want to identify as many of the ducks that have a defect as possible. Which evaluation metric would be appropriate here? **Recall.** Which model would be the best fit for this use case? **Model 3.**

In [380]:
positive_actuals = df_3[df_3.actual == 'Defect']

In [381]:
(positive_actuals.actual == positive_actuals.model1).mean()

0.5

In [382]:
(positive_actuals.actual == positive_actuals.model2).mean()

0.5625

In [383]:
(positive_actuals.actual == positive_actuals.model3).mean()

0.8125

In [384]:
recall_score(df_3.actual,df_3.model1,pos_label='Defect')

0.5

In [385]:
recall_score(df_3.actual,df_3.model2,pos_label='Defect')

0.5625

In [386]:
recall_score(df_3.actual,df_3.model3,pos_label='Defect')

0.8125

- Recently several stories in the local news have come out highlighting customers who received a rubber duck with a defect, and portraying C3 in a bad light. The PR team has decided to launch a program that gives customers with a defective duck a vacation to Hawaii. They need you to predict which ducks will have defects, but tell you the really don't want to accidentally give out a vacation package when the duck really doesn't have a defect. Which evaluation metric would be appropriate here? **Precision.** Which model would be the best fit for this use case? **Model 1.**

In [387]:
positive_predictions = df_3[df_3.model1 == 'Defect']
(positive_predictions.actual == positive_predictions.model1).mean()

0.8

In [389]:
positive_predictions = df_3[df_3.model2 == 'Defect']
(positive_predictions.actual == positive_predictions.model2).mean()

0.1

In [390]:
positive_predictions = df_3[df_3.model3 == 'Defect']
(positive_predictions.actual == positive_predictions.model3).mean()

0.13131313131313133

In [409]:
for col in df_3.columns[1:]:
    positive_predictions = df_3[df_3[col] == 'Defect']
    precision = (positive_predictions.actual == positive_predictions[col]).mean()
    print(f'{col} precision: {precision}')

model1 precision: 0.8
model2 precision: 0.1
model3 precision: 0.13131313131313133


In [392]:
precision_score(df_3.actual,df_3.model1,pos_label='Defect')

0.8

In [394]:
precision_score(df_3.actual,df_3.model2,pos_label='Defect')

0.1

In [393]:
precision_score(df_3.actual,df_3.model3,pos_label='Defect')

0.13131313131313133

### 4. You are working as a data scientist for Gives You Paws ™, a subscription based service that shows you cute pictures of dogs or cats (or both for an additional fee).

### At Gives You Paws, anyone can upload pictures of their cats or dogs. The photos are then put through a two step process. First an automated algorithm tags pictures as either a cat or a dog (Phase I). Next, the photos that have been initially identified are put through another round of review, possibly with some human oversight, before being presented to the users (Phase II).

### Several models have already been developed with the data, and [you can find their results here](https://ds.codeup.com/data/gives_you_paws.csv).

### Given this dataset, use pandas to create a baseline model (i.e. a model that just predicts the most common class) and answer the following questions:

In [420]:
df_4 = pd.read_csv('gives_you_paws.csv')

In [421]:
df_4

actual model1 model2 model3 model4
0       cat    cat    dog    cat    dog
1       dog    dog    cat    cat    dog
2       dog    cat    cat    cat    dog
3       dog    dog    dog    cat    dog
4       cat    cat    cat    dog    dog
...     ...    ...    ...    ...    ...
4995    dog    dog    dog    dog    dog
4996    dog    dog    cat    cat    dog
4997    dog    cat    cat    dog    dog
4998    cat    cat    cat    cat    dog
4999    dog    dog    dog    dog    dog

[5000 rows x 5 columns]

In [423]:
for col in df_4.columns[1:]:
    accuracy = (df_4.actual == df_4[col]).mean()
    print(f'{col} accuracy: {accuracy}')

model1 accuracy: 0.8074
model2 accuracy: 0.6304
model3 accuracy: 0.5096
model4 accuracy: 0.7426


In [264]:
positive_actuals = df_4[df_4.actual == 'Defect']

In [431]:
for col in df_4.columns[1:]:
    positive_actuals = df_4[df_4.actual == 'Defect']
    recall = (positive_actuals.actual == positive_actuals[col]).mean()
    print(f'{col} recall: {recall}')

model1 recall: nan
model2 recall: nan
model3 recall: nan
model4 recall: nan


In [267]:
print('\t\tModel One\tModel Two\tModel Three\tModel Four')
print(f'Accuracy:\t{accuracy1}\t\t{accuracy2}\t\t{accuracy3}\t\t{accuracy4}')
print(f'Precision:\t{precision1}\t\t{precision2}\t\t{precision3}\t\t{precision4}')
print(f'Recall:\t\t{recall1}\t\t{recall2}\t\t{recall3}\t\t{recall4}')

		Model One	Model Two	Model Three	Model Four
Accuracy:	0.81		0.63		0.51		0.74
Precision:	0.89		0.89		0.66		0.73
Recall:		0.8		0.49		0.51		0.96


In [268]:
model1 = pd.crosstab(df_4.actual,df_4.model1)
tp1 = model1.iloc[0,0]
tn1 = model1.iloc[1,1]
fp1 = model1.iloc[1,0]
fn1 = model1.iloc[0,1]

model2 = pd.crosstab(df_4.actual,df_4.model2)
tp2 = model2.iloc[0,0]
tn2 = model2.iloc[1,1]
fp2 = model2.iloc[1,0]
fn2 = model2.iloc[0,1]

model3 = pd.crosstab(df_4.actual,df_4.model3)
tp3 = model3.iloc[0,0]
tn3 = model3.iloc[1,1]
fp3 = model3.iloc[1,0]
fn3 = model3.iloc[0,1]

model4 = pd.crosstab(df_4.actual,df_4.model4)
tp4 = model4.iloc[0,0]
tn4 = model4.iloc[1,1]
fp4 = model4.iloc[1,0]
fn4 = model4.iloc[0,1]

In [270]:
accuracy1 = model_accuracy(tp1,tn1,fp1,fn1)
accuracy2 = model_accuracy(tp2,tn2,fp2,fn2)
accuracy3 = model_accuracy(tp3,tn3,fp3,fn3)
accuracy4 = model_accuracy(tp4,tn4,fp4,fn4)

In [271]:
precision1 = model_precision(tp1,fp1)
precision2 = model_precision(tp2,fp2)
precision3 = model_precision(tp3,fp3)
precision4 = model_precision(tp4,fp4)

In [272]:
recall1 = model_recall(tp1,fn1)
recall2 = model_recall(tp2,fn2)
recall3 = model_recall(tp3,fn3)
recall4 = model_recall(tp4,fn4)

In [273]:
print('\t\tModel One\tModel Two\tModel Three\tModel Four')
print(f'Accuracy:\t{accuracy1}\t\t{accuracy2}\t\t{accuracy3}\t\t{accuracy4}')
print(f'Precision:\t{precision1}\t\t{precision2}\t\t{precision3}\t\t{precision4}')
print(f'Recall:\t\t{recall1}\t\t{recall2}\t\t{recall3}\t\t{recall4}')

		Model One	Model Two	Model Three	Model Four
Accuracy:	0.81		0.63		0.51		0.74
Precision:	0.69		0.48		0.36		0.81
Recall:		0.82		0.89		0.51		0.35


- In terms of accuracy, how do the various models compare to the baseline model? Are any of the models better than the baseline?

In [274]:
df_4.actual.value_counts()

actual
dog    3254
cat    1746
Name: count, dtype: int64

In [275]:
3254 / (3254+1746)

0.6508

> 1 & 4

- Suppose you are working on a team that solely deals with dog pictures. Which of these models would you recommend?

- Suppose you are working on a team that solely deals with cat pictures. Which of these models would you recommend?

In [303]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import classification_report

In [284]:
print(accuracy_score(df_4.actual,df_4.model1))
print(accuracy_score(df_4.actual,df_4.model2))
print(accuracy_score(df_4.actual,df_4.model3))
print(accuracy_score(df_4.actual,df_4.model4))

0.8074
0.6304
0.5096
0.7426


In [295]:
precision_score(df_4.actual,df_4.model1,average=None)

array([0.68977218, 0.89002383])

In [296]:
precision_score(df_4.actual,df_4.model2,average=None)

array([0.48412204, 0.89317673])

In [297]:
precision_score(df_4.actual,df_4.model3,average=None)

array([0.35834671, 0.65988836])

In [298]:
precision_score(df_4.actual,df_4.model4,average=None)

array([0.80722892, 0.73124853])

In [299]:
precision_score(df_4.actual,df_4.model1,pos_label='dog')

0.8900238338440586

In [302]:
recall_score(df_4.actual,df_4.model1,pos_label='dog')

0.803318992009834

In [308]:
print(classification_report(df_4.actual,df_4.model1,target_names=['cat','dog']))

              precision    recall  f1-score   support

         cat       0.69      0.82      0.75      1746
         dog       0.89      0.80      0.84      3254

    accuracy                           0.81      5000
   macro avg       0.79      0.81      0.80      5000
weighted avg       0.82      0.81      0.81      5000

